### PR TITLE
update main.js

### PR DESCRIPTION
**Pull request by saejin-moon**
see the comments i left in the code.

### CODE REVIEW

**Review by ChickCoder123 — APPROVED** [review]
Thanks! I didn't know that there was an Error class.

**Comment by saejin-moon** [comment]
no merge?

**Comment by ChickCoder123** [comment]
I'm new to this. Sorry for the stup!d!ty, but how do I do that?

**Comment by saejin-moon** [comment]
:)
image
image

**Comment by ChickCoder123** [comment]
Done! :)

**Comment by saejin-moon** [comment]
thanks, :).

**Pull request merged**
